### ISSUE TITLE
Make SchemaView a mixin so we can use it in our own Schema's.

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/vng-api-common#1]
Among others, this allows us to do point the schema to the appropriate urlconf.

```python
DefaultSchemaView = get_schema_view(
    # ....
    urlconf='demo_api.api.v2.urls',
)

class SchemaView(ZDSSchemaViewMixin, DefaultSchemaView):
    pass
```

**Comment by sergei-maertens** [comment]
Hrm, I *think* this results in some complexities w/r to drf-yasg internals, so I'm afraid it won't be this straigtforward, unless we duplicate a lot of code which I am not a fan of :disappointed:
