### ISSUE TITLE
Command generate_swagger should accept version information

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/vng-api-common#2]
https://github.com/VNG-Realisatie/gemma-zaken-common/blob/c4e75bfbb1a89c1a67e4ddd5192900264437b141/zds_schema/management/commands/generate_swagger.py#L92-L95

Workaround was to add the urlconf here:

```python
        generator = OpenAPISchemaGenerator(
            info=info,
            url=api_url,
            urlconf='demo_api.api.v2.urls'
        )
```

But I noticed the original code allowed for a version to be passed. Not sure if that worked tho.

**Comment by sergei-maertens** [comment]
ec781d3c fixed this by inheriting the full signature of the original command (and updated to a more recent version of drf-yasg)
