### ISSUE TITLE
Breaking changes released as minor version

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/vng-api-common#227]
I see that #225 was merged and released via #226 as a minor release, but you did breaking changes that affect our projects.

Derived projects making use of vng-api-common (like https://github.com/open-zaak/open-zaak) are affected by this and you not adhering to semantic versioning. You are now forcing us to deal with massive changes in tooling _in a minor release_, and frankly, this is not acceptable.

Please yank the 1.11 release from PyPI and release this properly as 2.0, but it would also have been nice to check and give downstream projects time to test out these changes and adapt to them.

**Comment by MatthijsBekendam** [comment]
Thanks for letting us know, we will fix this as soon as possible.

**Comment by joerivrij** [comment]
@sergei-maertens. Version 1.11.0 has been removed both as a tag and as a Pypi project. I hope this fixes things and sorry for the mixup on our end.

**Comment by sergei-maertens** [comment]
Thanks!
