### ISSUE TITLE
Use constants instead of strings.

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/vng-api-common#23]
We should use constants instead of typing these over and over:

The notification component uses actions, like: 'list', 'read', etc.:
https://github.com/VNG-Realisatie/vng-api-common/pull/22/files#diff-fc3d84d47d024001d3713b8e75cdc904R51

And here we check for 'autorisations' as channel name. Maybe all "known" channel names should be in the project, just like the `ComponentTypes` enum is now:

https://github.com/VNG-Realisatie/vng-api-common/pull/22/files#diff-06900288ee127189c9c4ddc826634dddR95

**Comment by alextreme** [comment]
Maybe it's time for a Constant Object-identification Component <3

**Comment by sergei-maertens** [comment]
Not doing this for the DRF viewset actions. DRF itself has them hardcoded as strings as well, and as they are tied to method names, there's no point in defining them as constants and use those (you'd have to rename the methods anyway if something changes).
