### ISSUE TITLE
Permissions should not rely on the action attribute on a View since it's only used in ViewSets.

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/vng-api-common#28]
Basically the cause behind this comment:

https://github.com/VNG-Realisatie/vng-api-common/pull/27#pullrequestreview-235634058

The `action` attribute should not be needed at all, since it's a `View` and not a `ViewSet` but our permission approach expects the `action` attribute at all times.

**Comment by sergei-maertens** [comment]
In another project I had two maps - one is `action_map` and the other is `method_map`, if no action is available, then it looks at methods.
