### ISSUE TITLE
generate_schema with polymorphisms AssertionError

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/vng-api-common#44]
When using `PolymorphicSerializer`, running `generate_schema` fails due to some issues with polymorphisms and swagger2.0

```python
AssertionError: #/definitions/zaak already exists
```

**Comment by annashamray** [comment]
Polymorphic inspector was changed in https://github.com/VNG-Realisatie/vng-api-common/pull/57 
Please check if the issue is still actual

**Comment by sergei-maertens** [comment]
We can reopen if it still is
